@php
    $totalRevenue = $salesReport->sum('total');
    $avgDailySales = $salesReport->avg('total');
    $totalProducts = $productReport->count();
    $totalQuantity = $productReport->sum('total_quantity');
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Retailer Activity Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #222; margin: 0; padding: 0; }
        .header { background: #1976d2; color: #fff; padding: 24px 32px; border-top-left-radius: 12px; border-top-right-radius: 12px; }
        .header h2 { margin: 0 0 8px 0; font-size: 2rem; }
        .header p { margin: 0; font-size: 1rem; }
        .section { margin: 32px 32px 0 32px; }
        .section-title { font-size: 1.2rem; font-weight: bold; margin-bottom: 12px; color: #1976d2; }
        .info-table, .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        .info-table td { padding: 6px 12px; }
        .summary-table th, .summary-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .summary-table th { background: #f4f6fa; color: #1976d2; }
        .summary-table tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin: 32px 32px 0 32px; font-size: 0.95rem; color: #888; text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Retailer Activity Report</h2>
        <p>Summary of your business activities</p>
    </div>
    <div class="section">
        <table class="info-table">
            <tr>
                <td><strong>Name:</strong></td>
                <td>{{ $user->name }}</td>
                <td><strong>Email:</strong></td>
                <td>{{ $user->email }}</td>
            </tr>
            <tr>
                <td><strong>Date:</strong></td>
                <td>{{ now()->format('Y-m-d H:i') }}</td>
                <td><strong>Total Revenue:</strong></td>
                <td>UGX {{ number_format($totalRevenue) }}</td>
            </tr>
            <tr>
                <td><strong>Avg Daily Sales:</strong></td>
                <td>UGX {{ number_format($avgDailySales) }}</td>
                <td><strong>Total Products Sold:</strong></td>
                <td>{{ $totalProducts }}</td>
            </tr>
            <tr>
                <td><strong>Total Quantity Sold:</strong></td>
                <td>{{ $totalQuantity }}</td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="section">
        <div class="section-title">Sales Summary</div>
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Sales (UGX)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($salesReport as $sale)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($sale->date)->format('Y-m-d') }}</td>
                    <td>{{ number_format($sale->total) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="section">
        <div class="section-title">Product Performance</div>
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity Sold</th>
                    <th>Revenue (UGX)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($productReport as $product)
                <tr>
                    <td>{{ $product['name'] }}</td>
                    <td>{{ $product['total_quantity'] }}</td>
                    <td>{{ number_format($product['total_revenue']) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="footer">
        Generated by BWSCMS &mdash; {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html> 